#!/usr/bin/env ruby

$: << File.dirname(__FILE__) + '/lib'

require 'rubygems'
require 'irb'
require 'yaml'
require 'gitki'

SETTING = YAML.load(open("#{File.dirname(__FILE__)}/setting.yml"))
Gitki.setup(SETTING['git_store'])
include Gitki
IRB.start
